# Generated by Django 5.1.2 on 2024-10-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default=0.0, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
